<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MinesAutomatedExtension</AssemblyName>
    <RootNamespace>MinesAutomatedExtension</RootNamespace>
    <TargetFramework>net472</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" />
    <ProjectReference Include="..\MinesAutomated\MinesAutomated.csproj" />
  </ItemGroup>
</Project>