<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MinesAutomated</AssemblyName>
    <RootNamespace>MinesAutomated</RootNamespace>
    <TargetFramework>net472</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" />
  </ItemGroup>
</Project>